services:
  - type: web
    name: my-python-app
    runtime: python
    env: python
    buildCommand: apt-get update && apt-get install -y portaudio19-dev && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: "3.9"
